const shopItems = {
    
    'avatar_knight': { id: 'avatar_knight', name: 'Ritter Davion', type: 'avatar', value: 'knight.png', cost: 100 },
    'avatar_mage': { id: 'avatar_mage', name: 'Magierin', type: 'avatar', value: 'mage.png', cost: 110 },
    'avatar_robot': { id: 'avatar_robot', name: 'Robo-X', type: 'avatar', value: 'robot.png', cost: 90 },
    'avatar_ninja': { id: 'avatar_ninja', name: 'Schatten-Ninja', type: 'avatar', value: 'ninja.png', cost: 120 },
    'avatar_alien': { id: 'avatar_alien', name: 'Grüner Alien', type: 'avatar', value: 'alien.png', cost: 110 },
    'avatar_cyberpunk': { id: 'avatar_cyberpunk', name: 'Cyberpunk-Held', type: 'avatar', value: 'cyberpunk.png', cost: 140 },
    'avatar_vampire': { id: 'avatar_vampire', name: 'Nachtherrscher', type: 'avatar', value: 'vampire.png', cost: 130 },
    'avatar_dragon': { id: 'avatar_dragon', name: 'Feuerdrache', type: 'avatar', value: 'dragon.png', cost: 150 },
    'avatar_angel': { id: 'avatar_angel', name: 'Himmelswächter', type: 'avatar', value: 'angel.png', cost: 160 },
    'avatar_shadow': { id: 'avatar_shadow', name: 'Schattengeist', type: 'avatar', value: 'shadow.png', cost: 170 },
    'avatar_druid': { id: 'avatar_druid', name: 'Waldruferin', type: 'avatar', value: 'druid.png', cost: 115 },
    'avatar_samurai': { id: 'avatar_samurai', name: 'Sturmsamurai', type: 'avatar', value: 'samurai.png', cost: 125 },
    'avatar_phoenix': { id: 'avatar_phoenix', name: 'Phönixflamme', type: 'avatar', value: 'phoenix.png', cost: 160 },
    'avatar_ghost': { id: 'avatar_ghost', name: 'Verlorene Seele', type: 'avatar', value: 'ghost.png', cost: 100 },
    'avatar_witch': { id: 'avatar_witch', name: 'Hexe Morgra', type: 'avatar', value: 'witch.png', cost: 120 },
    'avatar_neon': { id: 'avatar_neon', name: 'Neon Runner', type: 'avatar', value: 'neon.png', cost: 130 },
    'avatar_elf': { id: 'avatar_elf', name: 'Lichtelfe', type: 'avatar', value: 'elf.png', cost: 110 },
    'avatar_zombie': { id: 'avatar_zombie', name: 'Untoter Joe', type: 'avatar', value: 'zombie.png', cost: 95 },
    'avatar_steampunk': { id: 'avatar_steampunk', name: 'Dampfingenieur', type: 'avatar', value: 'steampunk.png', cost: 135 },
    'avatar_fairy': { id: 'avatar_fairy', name: 'Waldfee', type: 'avatar', value: 'fairy.png', cost: 125 },
    'avatar_sorcerer': { id: 'avatar_sorcerer', name: 'Dunkelmagier', type: 'avatar', value: 'sorcerer.png', cost: 130 },
    'avatar_captain': { id: 'avatar_captain', name: 'Raumschiff-Captain', type: 'avatar', value: 'captain.png', cost: 115 },
    'avatar_gladiator': { id: 'avatar_gladiator', name: 'Arena-Krieger', type: 'avatar', value: 'gladiator.png', cost: 110 },
    'avatar_demon': { id: 'avatar_demon', name: 'Flammenfürst', type: 'avatar', value: 'demon.png', cost: 145 },
    'avatar_golem': { id: 'avatar_golem', name: 'Steingolem', type: 'avatar', value: 'golem.png', cost: 125 },
    'avatar_mirror': { id: 'avatar_mirror', name: 'Spiegelwandler', type: 'avatar', value: 'mirror.png', cost: 140 },
    'avatar_jester': { id: 'avatar_jester', name: 'Hofnarr Xilo', type: 'avatar', value: 'jester.png', cost: 100 },
    'avatar_tiger': { id: 'avatar_tiger', name: 'Kampftiger', type: 'avatar', value: 'tiger.png', cost: 105 },
    'avatar_frost': { id: 'avatar_frost', name: 'Frostwächter', type: 'avatar', value: 'frost.png', cost: 135 },
    'avatar_hacker': { id: 'avatar_hacker', name: 'Datenkrieger', type: 'avatar', value: 'hacker.png', cost: 115 },
    'avatar_djinn': { id: 'avatar_djinn', name: 'Wüstengeist', type: 'avatar', value: 'djinn.png', cost: 145 },
    'avatar_hunter': { id: 'avatar_hunter', name: 'Bestienjäger', type: 'avatar', value: 'hunter.png', cost: 120 },
    'avatar_mech': { id: 'avatar_mech', name: 'Kampf-Mech', type: 'avatar', value: 'mech.png', cost: 135 },
    'avatar_bard': { id: 'avatar_bard', name: 'Singender Barde', type: 'avatar', value: 'bard.png', cost: 95 },
    'avatar_monk': { id: 'avatar_monk', name: 'Kampfmönch', type: 'avatar', value: 'monk.png', cost: 100 },
    'avatar_valkyrie': { id: 'avatar_valkyrie', name: 'Valkyrie Freya', type: 'avatar', value: 'valkyrie.png', cost: 150 },


    'color_red': { id: 'color_red', name: 'Rot', type: 'chat_color', value: '#ff0000', cost: 50 },
    'color_green': { id: 'color_green', name: 'Grün', type: 'chat_color', value: '#00ff00', cost: 50 },
    'color_blue': { id: 'color_blue', name: 'Blau', type: 'chat_color', value: '#0000ff', cost: 50 },
    'color_gold': { id: 'color_gold', name: 'Gold', type: 'chat_color', value: '#FFD700', cost: 70 },
    'color_ice': { id: 'color_ice', name: 'Eisblau', type: 'chat_color', value: '#80dfff', cost: 60 },
    'color_sunset': { id: 'color_sunset', name: 'Sonnenuntergang', type: 'chat_color', value: '#ff6e40', cost: 60 },
    'color_neon_purple': { id: 'color_neon_purple', name: 'Neonlila', type: 'chat_color', value: '#c93cff', cost: 70 },
    'color_shadow': { id: 'color_shadow', name: 'Schattengrau', type: 'chat_color', value: '#2e2e2e', cost: 50 },
    'color_crystal': { id: 'color_crystal', name: 'Kristallklar', type: 'chat_color', value: '#a8f0ff', cost: 75 },
    'color_inferno': { id: 'color_inferno', name: 'Inferno-Rot', type: 'chat_color', value: '#ff3c38', cost: 80 },
    'color_midnight': { id: 'color_midnight', name: 'Mitternacht', type: 'chat_color', value: '#0d0221', cost: 65 },
    'color_plasma': { id: 'color_plasma', name: 'Plasma', type: 'chat_color', value: '#9d00ff', cost: 80 },
    'color_mint': { id: 'color_mint', name: 'Minze', type: 'chat_color', value: '#98ff98', cost: 55 },
    'color_lava': { id: 'color_lava', name: 'Lavaorange', type: 'chat_color', value: '#ff4500', cost: 70 },
    'color_ocean': { id: 'color_ocean', name: 'Ozean', type: 'chat_color', value: '#006994', cost: 60 },
    'color_rose': { id: 'color_rose', name: 'Rosé', type: 'chat_color', value: '#ffb6c1', cost: 50 },
    'color_amethyst': { id: 'color_amethyst', name: 'Amethyst', type: 'chat_color', value: '#9966cc', cost: 75 },
    'color_storm': { id: 'color_storm', name: 'Sturmgrau', type: 'chat_color', value: '#4a4a4a', cost: 60 },
    'color_cyberpunk': { id: 'color_cyberpunk', name: 'Cyberpunk', type: 'chat_color', value: '#ff00ff', cost: 85 },
    'color_jade': { id: 'color_jade', name: 'Jadegrün', type: 'chat_color', value: '#00a86b', cost: 65 },
    'color_bubblegum': { id: 'color_bubblegum', name: 'Bubblegum Pink', type: 'chat_color', value: '#ffc1cc', cost: 55 },
    'color_steel': { id: 'color_steel', name: 'Stahlgrau', type: 'chat_color', value: '#4682B4', cost: 60 },
    'color_pearl': { id: 'color_pearl', name: 'Perlweiß', type: 'chat_color', value: '#fdfdfe', cost: 80 },
    'color_nature': { id: 'color_nature', name: 'Naturgrün', type: 'chat_color', value: '#228B22', cost: 55 },
    'color_sand': { id: 'color_sand', name: 'Sand', type: 'chat_color', value: '#f4a460', cost: 50 },
    'color_cherry': { id: 'color_cherry', name: 'Kirschrot', type: 'chat_color', value: '#de3163', cost: 65 },
    'color_ghost': { id: 'color_ghost', name: 'Geisterweiß', type: 'chat_color', value: '#f8f8ff', cost: 60 },
    'color_coral': { id: 'color_coral', name: 'Koralle', type: 'chat_color', value: '#ff7f50', cost: 60 },
    'color_void': { id: 'color_void', name: 'Nichts', type: 'chat_color', value: '#1b1b1b', cost: 90 },
    'color_lime': { id: 'color_lime', name: 'Limettengrün', type: 'chat_color', value: '#32cd32', cost: 50 },
    'color_choco': { id: 'color_choco', name: 'Schokolade', type: 'chat_color', value: '#381819', cost: 55 },
    'color_emerald': { id: 'color_emerald', name: 'Smaragd', type: 'chat_color', value: '#50c878', cost: 75 },
    'color_firefly': { id: 'color_firefly', name: 'Glühwürmchen', type: 'chat_color', value: '#ccff00', cost: 65 },
    'color_pastel_sky': { id: 'color_pastel_sky', name: 'Pastellhimmel', type: 'chat_color', value: '#aec6cf', cost: 50 },
    'color_polar': { id: 'color_polar', name: 'Polarlicht', type: 'chat_color', value: '#5dfdcb', cost: 85 },
    'color_berry': { id: 'color_berry', name: 'Beere', type: 'chat_color', value: '#8a0253', cost: 60 },
    'color_uranium': { id: 'color_uranium', name: 'Urangrün', type: 'chat_color', value: '#baff29', cost: 75 },
    'color_obsidian': { id: 'color_obsidian', name: 'Obsidian', type: 'chat_color', value: '#1c1c1c', cost: 70 },

    'font_poppins': { id: 'font_poppins', name: 'Schriftart: Modern (Poppins)', type: 'font', value: 'font-poppins', cost: 300, description: 'Eine saubere und moderne Schrift.' },
    'font_roboto_mono': { id: 'font_roboto_mono', name: 'Schriftart: Tech (Roboto Mono)', type: 'font', value: 'font-roboto-mono', cost: 300, description: 'Eine coole, technische Monospace-Schrift.' },
    'font_merriweather': { id: 'font_merriweather', name: 'Schriftart: Klassisch (Merriweather)', type: 'font', value: 'font-merriweather', cost: 250, description: 'Eine elegante und klassische Serifenschrift.' },
    'font_lato': { id: 'font_lato', name: 'Schriftart: Klar (Lato)', type: 'font', value: 'font-lato', cost: 280, description: 'Eine sehr gut lesbare und freundliche Schrift.' },
    'font_oswald': { id: 'font_oswald', name: 'Schriftart: Kompakt (Oswald)', type: 'font', value: 'font-oswald', cost: 280, description: 'Eine markante, schmale Schrift für Überschriften.' },
    'font_caveat': { id: 'font_caveat', name: 'Schriftart: Handschrift (Caveat)', type: 'font', value: 'font-caveat', cost: 320, description: 'Eine lockere, persönliche Handschrift.' },
    'font_lato': { id: 'font_lato', name: 'Schriftart: Klar (Lato)', type: 'font', value: 'font-lato', cost: 280, description: 'Eine sehr gut lesbare und freundliche Schrift.' },
    'font_oswald': { id: 'font_oswald', name: 'Schriftart: Kompakt (Oswald)', type: 'font', value: 'font-oswald', cost: 280, description: 'Eine markante, schmale Schrift für Überschriften.' },
    'font_caveat': { id: 'font_caveat', name: 'Schriftart: Handschrift (Caveat)', type: 'font', value: 'font-caveat', cost: 320, description: 'Eine lockere, persönliche Handschrift.' },
    'font_nunito': { id: 'font_nunito', name: 'Schriftart: Rundlich (Nunito)', type: 'font', value: 'font-nunito', cost: 290, description: 'Eine weiche, abgerundete und einladende Schrift.' },
    'font_montserrat': { id: 'font_montserrat', name: 'Schriftart: Urban (Montserrat)', type: 'font', value: 'font-montserrat', cost: 310, description: 'Eine geometrische Schrift, inspiriert von alten Postern aus Buenos Aires.' },
    'font_playfair': { id: 'font_playfair', name: 'Schriftart: Elegant (Playfair Display)', type: 'font', value: 'font-playfair', cost: 330, description: 'Eine kontrastreiche, elegante Schrift für besondere Anlässe.' },
    'font_source_code': { id: 'font_source_code', name: 'Schriftart: Hacker (Source Code Pro)', type: 'font', value: 'font-source-code', cost: 300, description: 'Die ultimative Schrift für alle Programmier-Fans.' },
    'font_bebas_neue': { id: 'font_bebas_neue', name: 'Schriftart: Blockbuster (Bebas Neue)', type: 'font', value: 'font-bebas-neue', cost: 320, description: 'Eine extrem populäre, reine Großbuchstaben-Schrift.' },
    'font_pacifico': { id: 'font_pacifico', name: 'Schriftart: Retro (Pacifico)', type: 'font', value: 'font-pacifico', cost: 310, description: 'Eine wunderschöne, pinselartige Schreibschrift im 50er-Jahre-Stil.' },
    'font_cinzel': { id: 'font_cinzel', name: 'Schriftart: Römisch (Cinzel)', type: 'font', value: 'font-cinzel', cost: 340, description: 'Inspiriert von klassischen römischen Inschriften. Majestätisch und zeitlos.' },

    'fx-fire': { id: 'fx-fire', name: 'Feuer-Aura', type: 'chat_fx', value: 'fx-fire', cost: 350, description: 'Dein Name brennt mit animierten Flammen und Funken.' },
    'fx-winter': { id: 'fx-winter', name: 'Winter-Aura', type: 'chat_fx', value: 'fx-winter', cost: 350, description: 'Dein Name glüht eisig und wird von Schneeflocken umschwirrt.' },
    'fx-smoke': { id: 'fx-smoke', name: 'Rauch-Aura', type: 'chat_fx', value: 'fx-smoke', cost: 350, description: 'Mysteriöser Rauch steigt von deinem Namen auf.' },
    'fx-galaxy': { id: 'fx-galaxy', name: 'Galaxie-Aura', type: 'chat_fx', value: 'fx-galaxy', cost: 500, description: 'Planeten umkreisen deinen galaktisch leuchtenden Namen.' },    
};

module.exports = shopItems;